config/routes.rb
Rails.application.routes.draw do

  get 'public_items_search' => 'public/items#search', as: 'public_items_search'
  get 'admin_items_search' => 'admin/items#search', as: 'admin_items_search'

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/hide' => 'public/customers#hide'


  scope module: :public do

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create,] do
      collection do
        delete  'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end
    post 'orders/confirm'

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

  end

  namespace :admin do

    get '/' => 'homes#top'

    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    resources :genres, only:[:index, :create, :edit, :update]

    resources :customers, only:[:index, :show, :edit, :update]

    resources :orders, only:[:show, :update] do
      # patch 'order_details/:id' => 'order_details#update', as: 'order_detail'
      resources :order_details, only:[:update]
    end

  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def  address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price*amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


has_many :cart_items, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :addresses, dependent: :destroy

  def name_display
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def with_tax_price
     (price * 1.1).floor
  end

  def self.search(keyword)
    Item.where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price*amount
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number,:email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:name].present?
      @orders = Customer.find(params[:name]).orders.page(params[:page]).per(10)
      @list_name = Customer.find(params[:name]).name_display + "さんの注文履歴"
    else
      @orders = Order.page(params[:page]).per(10)
      @list_name = "注文履歴一覧"
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(10)
    @keyword = params[:keyword]
    render "index"
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item  = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_session_path
    elsif resource_or_scope == :customer
      root_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-12">
      <h3><%= @customer.name_display %>さんの会員情報編集</h3>
    </div>
  </div>

  <div class="my-3">
    <div class="row">
      <div class="col-md-3 col-form-label">
        <p>会員ID</p>
      </div>
      <div class="col-md-9 col-form-label">
        <span><%= @customer.id %></span>
      </div>
    </div>
    <%= form_with model: @customer, url: admin_customer_path do |f| %>
      <div class="form-group row">
        <div class="col-md-3">
          <p class="col-form-label">名前</p>
        </div>
        <div class="col-md-9">
          <%= f.text_field :last_name, placeholder: "姓", class: "mr-4" %>
          <%= f.text_field :first_name, placeholder: "名" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <p class="col-form-label">フリガナ</p>
        </div>
        <div class="col-md-9">
          <%= f.text_field :last_name_kana, class: "mr-4" %>
          <%= f.text_field :first_name_kana %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :postal_code, "郵便番号", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :postal_code %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :address, "住所", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :address, size: "50" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :telephone_number, "電話番号", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.text_field :telephone_number %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :email, "メールアドレス", class: "col-form-label" %>
        </div>
        <div class="col-md-9">
          <%= f.email_field :email, autocomplete: "email" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>会員ステータス</p>
        </div>
        <div class="col-md-9">
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted_false, "有効", class: "mr-4" %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted_true, "退会" %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 text-center"></div>
        <div class="col-md-9">
          <%= f.submit "変更を保存", class: "btn btn-success px-5" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>会員一覧</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mt-2">
      <table class="table table-hover border-bottom">
        <thead>
          <tr class="table-secondary">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
               <%= customer.id %>
              </td>
              <td>
                <%= link_to customer.name_display, admin_customer_path(customer.id), class: "text-dark" %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_deleted == false %>
                <span class="text-success"><strong>有効</strong></span>
                <% else %>
                <span class="text-black-50"><strong>退会</strong></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3><%= @customer.name_display %>さんの会員詳細</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-form-label">
      <p>会員ID</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.id %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>氏名</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.last_name %>　<%= @customer.first_name %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>フリガナ</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>郵便番号</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.postal_code %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>住所</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.address %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>電話番号</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.telephone_number %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>メールアドレス</p>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @customer.email %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <p>会員ステータス</p>
    </div>
    <div class="col-md-9 col-form-label">
      <% if @customer.is_deleted == false %>
      <span class="text-success"><strong>有効</strong></span>
      <% else %>
      <span class="text-black-50"><strong>退会</strong></span>
      <% end %>
    </div>

    <div class="col-md-3 col-form-label">
    </div>
    <div class="col-md-9 col-form-label">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success col-md-3" %>
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary col-md-4 ml-4" %>
    </div>
  </div>
</div>