config/routes.rb
Rails.application.routes.draw do

  get 'public_items_search' => 'public/items#search', as: 'public_items_search'
  get 'admin_items_search' => 'admin/items#search', as: 'admin_items_search'

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/hide' => 'public/customers#hide'


  scope module: :public do

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create,] do
      collection do
        delete  'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end
    post 'orders/confirm'

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

  end

  namespace :admin do

    get '/' => 'homes#top'

    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    resources :genres, only:[:index, :create, :edit, :update]

    resources :customers, only:[:index, :show, :edit, :update]

    resources :orders, only:[:show, :update] do
      # patch 'order_details/:id' => 'order_details#update', as: 'order_detail'
      resources :order_details, only:[:update]
    end

  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def  address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price*amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


has_many :cart_items, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :addresses, dependent: :destroy

  def name_display
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def with_tax_price
     (price * 1.1).floor
  end

  def self.search(keyword)
    Item.where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price*amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:name].present?
      @orders = Customer.find(params[:name]).orders.page(params[:page]).per(10)
      @list_name = Customer.find(params[:name]).name_display + "さんの注文履歴"
    else
      @orders = Order.page(params[:page]).per(10)
      @list_name = "注文履歴一覧"
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(10)
    @keyword = params[:keyword]
    render "index"
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item  = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_session_path
    elsif resource_or_scope == :customer
      root_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>ジャンル編集</h3>
    </div>
  </div>

  <%= form_with model: @genre, url: admin_genre_path do |f| %>
  <div class="row">
    <div class="col-md-12 col-form-label">
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name, class: "ml-5" %>
      <%= f.submit '変更を保存', class: "ml-5 btn btn-success btn-sm px-3" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>ジャンル一覧・追加</h3>
    </div>
  </div>

  <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
  <div class="row">
    <div class="col-md-12 col-form-label">
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name, class: "ml-5" %>
      <%= f.submit '新規登録', class: "ml-5 btn btn-success btn-sm px-3" %>
    </div>
  </div>
  <% end %>

  <div class="row mt-5">
    <div class="col-md-4">
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th class="text-center">ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td class="align-middle"><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>商品編集</h3>
    </div>
  </div>
  <%= form_with model: @item, url: admin_item_path  do |f| %>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :image, "商品画像" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :name, "商品名" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_field :name, placeholder: '商品名', size: "40" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :introduction, "商品説明" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_area :introduction, placeholder: 'ここに説明文を記述します', size: "40x8" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :genre_id, "ジャンル" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: '--選択してください--' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :price, "税抜価格" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_field :price, placeholder: '1000', size: "40" %>円
    </div>
  </div>

  <div class="form-group row col-form-label">
    <div class="col-md-3">
      <%= f.label :is_active, "販売ステータス" %>
    </div>
    <div class="col-md-9">
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active_true, "販売中", class: "mr-4" %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active_false, "販売停止中" %>
    </div>
  </div>

  <div class="form-group row col-form-label">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
      <%= f.submit '新規登録', class: "btn btn-success px-4" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-6">
      <h3>商品一覧</h3>
    </div>
    <div class="col-md-6 text-right">
      <%= link_to new_admin_item_path, class: "btn btn-light rounded-circle shadow ", style: "width:3rem;height:3rem;" do %>
        <div class="d-flex align-items-center justify-content-center h3 ">＋</div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead>
          <tr class="table-secondary">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
               <%= item.id %>
              </td>
              <td class="align-middle text-decoration-underline">
                <%= link_to item.name, admin_item_path(item.id), class: "text-dark" %>
              </td>
              <td class="align-middle">
                <%= item.price.to_s(:delimited) %>
              </td>
              <td class="align-middle">
                <%= item.genre.name %>
              </td>
              <td class="align-middle">
                <% if item.is_active == true %>
                <span class="text-success"><strong>販売中</strong></span>
                <% else %>
                <span class="text-black-50"><strong>販売停止中</strong></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 d-flex justify-content-center">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>商品新規登録</h3>
    </div>
  </div>
  <%= form_with model: @item, url: admin_items_path do |f| %>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :image, "商品画像" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :name, "商品名" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_field :name, placeholder: '商品名', size: "40" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :introduction, "商品説明" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_area :introduction, placeholder: 'ここに説明文を記述します', size: "40x8" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :genre_id, "ジャンル" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: '--選択してください--' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-3 col-form-label">
      <%= f.label :price, "税抜価格" %>
    </div>
    <div class="col-md-9 col-form-label">
      <%= f.text_field :price, placeholder: '1000', size: "40" %>円
    </div>
  </div>

  <div class="form-group row col-form-label">
    <div class="col-md-3">
      <%= f.label :is_active, "販売ステータス" %>
    </div>
    <div class="col-md-9">
      <%= f.radio_button :is_active, :true %>
      <%= f.label :is_active_true, "販売中", class: "mr-4" %>
      <%= f.radio_button :is_active, :false %>
      <%= f.label :is_active_false, "販売停止中" %>
    </div>
  </div>

  <div class="form-group row col-form-label">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
      <%= f.submit '新規登録', class: "btn btn-success px-4" %>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>商品詳細</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.image, size: "300x200" %>
    </div>
    <div class="col-md-6">

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>商品名</p>
        </div>
        <div class="col-md-9 col-form-label">
          <span class="h5"><%= @item.name %></span>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>商品説明</p>
        </div>
        <div class="col-md-9 col-form-label">
          <span class="h5"><%= @item.introduction %></span>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>ジャンル</p>
        </div>
        <div class="col-md-9 col-form-label">
          <span class="h5"><%= @item.genre.name %></span>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>税込価格<br>(税抜価格)</p>
        </div>
        <div class="col-md-9 col-form-label d-flex align-items-center">
          <span class="h5"><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</span>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3 col-form-label">
          <p>販売ステータス</p>
        </div>
        <div class="col-md-9 col-form-label">
          <% if @item.is_active == true %>
          <span class="text-success h5"><strong>販売中</strong></span>
          <% else %>
          <span class="text-black-50 h5"><strong>販売停止中</strong></span>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-6 text-center">
           <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success w-100" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row my-4">
    <div class="col-md-4">
      <h3>注文履歴詳細</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-form-label">
      <h5><strong>購入者</strong></h5>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @order.customer.name_display %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <h5><strong>注文日</strong></h5>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @order.created_at.strftime('%Y/%m/%d') %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <h5><strong>配送先</strong></h5>
    </div>
    <div class="col-md-9 col-form-label">
      <span>〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <h5><strong>支払方法</strong></h5>
    </div>
    <div class="col-md-9 col-form-label">
      <span><%= @order.payment_method_i18n %></span>
    </div>

    <div class="col-md-3 col-form-label">
      <h5><strong>注文ステータス</strong></h5>
    </div>
    <div class="col-md-5 col-form-label">
      <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
        <%= f.select :status, Order.statuses_i18n.invert, {prompt: false} %>
        <%= f.submit "更新", class: "btn btn-success btn-sm ml-4" %>
      <% end %>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-8">
      <table class="table border-bottom">
        <thead>
          <tr class="table-secondary">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% total = 0 %>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price.to_s(:delimited) %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.subtotal.to_s(:delimited) %></td>
              <%= form_with model: [@order, order_detail], url: admin_order_order_detail_path(@order,order_detail), method: :patch do |f| %>
                <td><%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {prompt: false} %></td>
                <td><%= f.submit "更新", class: "btn btn-success btn-sm" %></td>
              <% end %>
            </tr>
            <% total += order_detail.subtotal %>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 d-flex align-items-end">
      <div class="row ml-4">

        <div class="col-md-6">
          <h5><strong>商品合計</strong></h5>
        </div>
        <div class="col-md-6">
          <h5><%= total.to_s(:delimited) %>円</h5>
        </div>

        <div class="col-md-6">
          <h5><strong>送料</strong></h5>
        </div>
        <div class="col-md-6">
          <h5><%= @order.shipping_cost %>円</h5>
        </div>

        <div class="col-md-6">
          <h5><strong>請求金額合計</strong></h5>
        </div>
        <div class="col-md-6">
          <h5><strong><%= @order.total_payment.to_s(:delimited) %>円</strong></h5>
        </div>

      </div>
    </div>
  </div>
</div>