config/routes.rb
Rails.application.routes.draw do

  get 'public_items_search' => 'public/items#search', as: 'public_items_search'
  get 'admin_items_search' => 'admin/items#search', as: 'admin_items_search'

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'

  get 'customers/my_page' => 'public/customers#show'
  get 'customers/information/edit' => 'public/customers#edit'
  patch 'customers/information' => 'public/customers#update'
  get 'customers/unsubscribe' => 'public/customers#unsubscribe'
  patch 'customers/hide' => 'public/customers#hide'


  scope module: :public do

    resources :items, only:[:index, :show]

    resources :cart_items, only:[:index, :update, :destroy, :create,] do
      collection do
        delete  'destroy_all'
      end
    end

    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        get 'complete'
      end
    end
    post 'orders/confirm'

    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

  end

  namespace :admin do

    get '/' => 'homes#top'

    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    resources :genres, only:[:index, :create, :edit, :update]

    resources :customers, only:[:index, :show, :edit, :update]

    resources :orders, only:[:show, :update] do
      # patch 'order_details/:id' => 'order_details#update', as: 'order_detail'
      resources :order_details, only:[:update]
    end

  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def  address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price*amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


has_many :cart_items, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :addresses, dependent: :destroy

  def name_display
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  def with_tax_price
     (price * 1.1).floor
  end

  def self.search(keyword)
    Item.where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

  def subtotal
    price*amount
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    if params[:name].present?
      @orders = Customer.find(params[:name]).orders.page(params[:page]).per(10)
      @list_name = Customer.find(params[:name]).name_display + "さんの注文履歴"
    else
      @orders = Order.page(params[:page]).per(10)
      @list_name = "注文履歴一覧"
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def search
    @items = Item.search(params[:keyword]).page(params[:page]).per(10)
    @keyword = params[:keyword]
    render "index"
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item  = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_session_path
    elsif resource_or_scope == :customer
      root_path
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-light bg-light border-bottom">
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <div class="col-md-2">
            <a class="navbar-brand display-4" href="/"><span>ながのCAKE</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="col-md-10">
            <div class="row">
              <div class="col-md-12">
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                  <% if admin_signed_in? %>
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark border border-dark rounded m-2 px-4' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark border border-dark rounded m-2 px-4' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border border-dark rounded m-2 px-3' %>
                    </li>
                  </ul>
                  <% elsif customer_signed_in? %>
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark border border-dark rounded m-2' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "商品一覧", items_path, class: 'nav-link text-dark border border-dark rounded m-2 px-3' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "カート", cart_items_path, class: 'nav-link text-dark border border-dark rounded m-2 px-4' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark border border-dark rounded m-2' %>
                    </li>
                  </ul>
                  <% else %>
                  <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <%= link_to "About" , about_path, class: 'nav-link text-dark border border-dark rounded m-2 px-4' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "商品一覧", items_path, class: 'nav-link text-dark border border-dark rounded m-2 px-3' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark border border-dark rounded m-2 px-3' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark border border-dark rounded m-2 px-3' %>
                    </li>
                  </ul>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="row">
              <% if admin_signed_in? %>
              <div class="col-md-12 mt-3 text-right">
                <%= form_with url: admin_items_search_path, method: :get do |f| %>
                  <%= f.text_field :keyword, value: @keyword, placeholder: 'Search' %>
                  <%= f.submit "検索", class: 'btn btn-primary' %>
                <% end %>
              </div>
              <% else %>
              <div class="col-md-12 mt-3">
                <div class="row">
                  <div class="col-md-4">
                    <span>
                      <% if customer_signed_in? %>
                      <p class="">ようこそ、<%= current_customer.last_name %>さん！</p>
                      <% end %>
                    </span>
                  </div>
                  <div class="col-md-8 text-right">
                    <%= form_with url: public_items_search_path, method: :get do |f| %>
                      <%= f.text_field :keyword, value: @keyword, placeholder: 'Search' %>
                      <%= f.submit "検索", class: 'btn btn-primary' %>
                    <% end %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer class="bg-light border-top mt-5">
      <div class="container mt-5">
        <div class="row" style="height: 15px">
        </div>
      </div>
    </footer>
  </body>
</html>